const label Cv         =0;                        
const label Cp         =1;
const label Cp_MCv     =2;
const label Gamma      =3;
const label Pinf       =4;
const label Ener_Ref   =5;
// Values ​​calculated by code
const label Gamma_Mu   =6;
const label Gamma_Pinf =7;
const label Gamma_Pu   =8;
const label Rap_Gam_Pu =9;
const label Rap_Gam_Mu =10;
const label Covol      =11;
const label Emissivite =12;
const label Prandtl    =13;
const label Cond_Therm =14;
const label Visc_Dyn   =15;
const label Wmol       =16;
